// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTrack(arg1, arg2) {
  return window['go']['main']['App']['AddTrack'](arg1, arg2);
}

export function DeleteTrack(arg1) {
  return window['go']['main']['App']['DeleteTrack'](arg1);
}

export function GetAudioLevels() {
  return window['go']['main']['App']['GetAudioLevels']();
}

export function GetInstruments() {
  return window['go']['main']['App']['GetInstruments']();
}

export function GetRecentSongs() {
  return window['go']['main']['App']['GetRecentSongs']();
}

export function GetSong(arg1) {
  return window['go']['main']['App']['GetSong'](arg1);
}

export function SaveQuickIdea(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveQuickIdea'](arg1, arg2, arg3);
}

export function SaveSong(arg1) {
  return window['go']['main']['App']['SaveSong'](arg1);
}

export function StartRecording(arg1, arg2) {
  return window['go']['main']['App']['StartRecording'](arg1, arg2);
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function UpdateTrack(arg1) {
  return window['go']['main']['App']['UpdateTrack'](arg1);
}
