// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetRecentSongs():Promise<Array<models.Song>>;

export function GetSong(arg1:number):Promise<models.Song>;

export function SaveQuickIdea(arg1:number,arg2:string,arg3:string):Promise<number>;
