// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {recorder} from '../models';

export function AddTrack(arg1:number,arg2:string):Promise<models.Track>;

export function DeleteTrack(arg1:number):Promise<void>;

export function GetAudioLevels():Promise<number>;

export function GetAudioVersionsForSong(arg1:number):Promise<Array<models.AudioVersion>>;

export function GetAudioVersionsForTrack(arg1:number):Promise<Array<models.AudioVersion>>;

export function GetAvailableDrivers():Promise<Array<string>>;

export function GetCurrentDriver():Promise<string>;

export function GetInputDevices():Promise<Array<recorder.AudioDevice>>;

export function GetInstruments():Promise<Array<models.Instrument>>;

export function GetPlaybackDuration():Promise<number>;

export function GetPlaybackPosition():Promise<number>;

export function GetRecentSongs():Promise<Array<models.Song>>;

export function GetSong(arg1:number):Promise<models.Song>;

export function PauseAudio():Promise<void>;

export function PlayAudio(arg1:string):Promise<void>;

export function SaveQuickIdea(arg1:number,arg2:string,arg3:string):Promise<number>;

export function SaveSong(arg1:models.Song):Promise<models.Song>;

export function SeekAudio(arg1:number):Promise<void>;

export function SetAudioDriver(arg1:string):Promise<void>;

export function SetAudioVolume(arg1:number):Promise<void>;

export function StartRecording(arg1:number,arg2:string,arg3:string):Promise<void>;

export function StopRecording(arg1:number):Promise<models.AudioVersion>;

export function UpdateTrack(arg1:models.Track):Promise<void>;
