// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddTrack(arg1:number,arg2:string):Promise<models.Track>;

export function DeleteTrack(arg1:number):Promise<void>;

export function GetInstruments():Promise<Array<models.Instrument>>;

export function GetRecentSongs():Promise<Array<models.Song>>;

export function GetSong(arg1:number):Promise<models.Song>;

export function SaveQuickIdea(arg1:number,arg2:string,arg3:string):Promise<number>;

export function SaveSong(arg1:models.Song):Promise<models.Song>;

export function UpdateTrack(arg1:models.Track):Promise<void>;
